### ISSUE TITLE
Add time stamps to trace messages

### ISSUE THREAD

**Issue by theAgingApprentice** [theAgingApprentice/HexaFloorRide#122]
For  some types of debugging, such as bus messaging, it is useful to have accurate timing information on when a message was issued. We should add this information as an option for the format of our messages.

**Comment by nerdoug** [comment]
This has been implemented and merged. Inclusion of the timestamp is controlled by this entry in global_variables.cpp:
```
#define t$timestamps 1            // if defined, adds timestamps, in millis(), to all trace messages
                                    // comment out above line to remove timestamps from trace messages
```
The timestamp is from millis() and appears in square brackets in the trace:

     ` M) oneSec{14}[15962]>  CPU: 0.65  /Oled: 0.0  0.0 0 /MQTT: 0.0  0.0 0 /webMon: 0.5  0.1 0 /Flow: 0.0  0.0 `
