### ISSUE TITLE
Decide where to put the constant values for the leg dimensions

### ISSUE THREAD

**Issue by theAgingApprentice** [theAgingApprentice/HexaFloorRide#17]
Need to centralize all the places where robot physical dimension information is stored, and do it in a way that's compatible with the modified source file structure that came out of issue 93

**Comment by nerdoug** [comment]
Based on the new file structure, we should handle physical dimension info as follows:

symbols that represent the actual dimensions should go in global_variables.cpp. This could be either run time variables, or compile time symbols, i.e. macros defined via #define. I favour doing both in global_variables.cpp: defining macros to represent the actual measurements, and defining the variables that are used at run time as well, as global variables.

The necessary run time variables are initialized, using combinations of the macros, in setup a routine, or routines, in configDetails.cpp. If these were only used by one function, or bag of functions, it might be reasonable to have the setup done there, but I don't think that's the case for physical dimensions, so configDetails.cpp is the best place.

I'll open a new ticket (done: 118)  to implement the handling of dimensions as described above.
